apiVersion: v1
kind: ConfigMap
metadata:
  name: delicious-config
data:
  GREETING: Hello from helm chart.
---
apiVersion: v1
kind: Secret
metadata:
  name: delicious-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "User Id=%s;Password=%s;Host=%s;Port=%s;Database=%s;Integrated Security = False;" .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort .Values.externalPostgresql.postgresqlDatabase  | b64enc | quote }}
