apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "delicious-chart.fullname" . }}
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "delicious-chart.fullname" . }}
            servicePort: {{ .Values.service.port }}