apiVersion: apps/v1
kind: Deployment
metadata:
    name: delicious-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: delicious-app
    template:
       metadata:
          labels:
             app: delicious-app
       spec:
          containers:
          - name: delicious
            image: gr1feel/delicious-service:homework_2_v7
            ports:
              - name: webapp
                containerPort: 8000
            livenessProbe:
              httpGet:
                port: webapp
                path: /
            readinessProbe:
              httpGet:
                port: webapp
                path: /health
            env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: delicious-secret
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: delicious-config
                  key: GREETING
