apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: delicious-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp/.*/(.*)
          backend:
            serviceName: delicious-service
            servicePort: 8000
